# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\")\n\tListPairs\x12\x1c\n\x05pairs\x18\x01 \x03(\x0b\x32\r.KeyValuePair\"\x1c\n\x0eStatusResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2X\n\x0b\x44ictService\x12)\n\x07\x41\x64\x64Pair\x12\r.KeyValuePair\x1a\x0f.StatusResponse\x12\x1e\n\x08GetPairs\x12\x06.Empty\x1a\n.ListPairsb\x06proto3')



_KEYVALUEPAIR = DESCRIPTOR.message_types_by_name['KeyValuePair']
_LISTPAIRS = DESCRIPTOR.message_types_by_name['ListPairs']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIR,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:KeyValuePair)
  })
_sym_db.RegisterMessage(KeyValuePair)

ListPairs = _reflection.GeneratedProtocolMessageType('ListPairs', (_message.Message,), {
  'DESCRIPTOR' : _LISTPAIRS,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:ListPairs)
  })
_sym_db.RegisterMessage(ListPairs)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_DICTSERVICE = DESCRIPTOR.services_by_name['DictService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUEPAIR._serialized_start=13
  _KEYVALUEPAIR._serialized_end=55
  _LISTPAIRS._serialized_start=57
  _LISTPAIRS._serialized_end=98
  _STATUSRESPONSE._serialized_start=100
  _STATUSRESPONSE._serialized_end=128
  _EMPTY._serialized_start=130
  _EMPTY._serialized_end=137
  _DICTSERVICE._serialized_start=139
  _DICTSERVICE._serialized_end=227
# @@protoc_insertion_point(module_scope)
